emailService/models/models.py
from ..db.db import db
from sqlalchemy.orm import validates


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    bookings_id = db.Column(db.String(120), unique=True)
    cliniko_id = db.Column(db.String(120), nullable=False)

    def __repr__(self):
        return f'<User {self.username}>'


class Bookings(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    appointment_type_ID = db.Column(db.String(500), nullable=False)
    starts_at = db.Column(db.String(30), nullable=False)
    ends_at = db.Column(db.String(30), nullable=False)
    updated_at = db.Column(db.String(30), nullable=False)
    cliniko_id = db.Column(db.String(120), nullable=False)
    user_id = db.Column(db.String(120), unique=True)
    appointment_type_str = db.Column(db.String(250), nullable=False)
    db.Column(db.Boolean(), nullable=True, default=False)

    def __repr__(self):
        return f"Appointment type {self.appointment_type}"


class Emails(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    isShown = db.Column(db.Boolean(), nullable=True, default=False)
    template = db.Column(db.String(80), nullable=False)
    content = db.Column(db.TEXT, nullable=True)
    username = db.Column(db.String(80), nullable=False)
    user_cliniko_id = db.Column(db.String(120), nullable=False)
    booking_cliniko_id = db.Column(db.String(120), nullable=True)
    template_color_code = db.Column(db.String(80), nullable=True)
    date = db.Column(db.String(80), nullable=False)
    isSent = db.Column(db.Boolean(), nullable=False, default=False)


class EmailTemplates(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=True)
    color = db.Column(db.String(25), nullable=False, default="#e38901")
    jsonConstruct = db.Column(db.JSON, nullable=False)
    imageUrl = db.Column(db.String(255))

    @validates('name')
    def validate_name(self, key, name):
        if not name:
            raise ValueError("Name cannot be empty")
        return name

    @validates('content')
    def validate_description(self, key, description):
        # Add more complex validation logic if needed
        if not description:
            raise ValueError("Content cannot be empty")

        return description

emailService/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length


class NewTemplate(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=255)],
                        render_kw={"class": "form-control template-name"})
    content = TextAreaField('Content', validators=[DataRequired()],
                            render_kw={"class": "form-control template-content", "id": "input-message"})

emailService/__init__.py
# __init__.py

from .emailService import app, images, csrf

emailService/db/__init__.py
from .db import db, init_app

emailService/routes.py
from datetime import datetime, timedelta
from apscheduler.schedulers.background import BackgroundScheduler
from flask import render_template
from enum import Enum
from .utilities.get_data import get_data
from .utilities.time_utilities import get_time_range_str
from .utilities.filterBody import filter_field
from flask import jsonify
from .db import db
from flask_migrate import Migrate
from flask import Flask
from .models.models import Emails, EmailTemplates, User, Bookings
from flask import Blueprint
from .forms.forms import NewTemplate

email_blueprint = Blueprint('emailService', __name__, url_prefix='/emailService', template_folder='templates',
                            static_folder='static')


@email_blueprint.route("/")
def index():
    today_date = datetime.now().strftime('%Y-%m-%d')
    bookings = Bookings.query.filter(
        func.DATE(func.STR_TO_DATE(Bookings.ends_at, '%Y-%m-%dT%H:%i:%SZ')) == today_date
    ).all()
    patient_list = []
    for booking in bookings:
        user = User.query.filter_by(ciliniko_id=booking.user_id)
        patient_list.append(user)

    emailTemplates = EmailTemplates.query.all()
    emailsSent = Emails.query.filter_by(isSent=True)
    scheduledEmails = Emails.query.filter_by(isSent=False)

    newTemplateForm = NewTemplate()
    return render_template("emails.html", emailTemplates=emailTemplates, emailsSent=emailsSent, form=newTemplateForm,
                           scheduledEmails=scheduledEmails)


@email_blueprint.route('/template-creator')
def template_creator():
    newTemplateForm = NewTemplate()
    return render_template("template_creator.html", form=newTemplateForm)


@email_blueprint.route('/templates')
def templates():
    emailTemplates = EmailTemplates.query.all()

    return render_template("templates.html", templates=emailTemplates)


@email_blueprint.route('/edit_template/<template_name>', methods=['GET'])
def edit_template(template_name):
    template = EmailTemplates.query.filter_by(name=template_name).first_or_404()
    # Convert the EmailTemplates object to a dictionary
    template_data = {
        'id': template.id,
        'name': template.name,
        'jsonConstruct': template.jsonConstruct,
        'color': template.color,
        'imageUrl': template.imageUrl
        # Add other attributes as needed
    }
    newTemplateForm = NewTemplate()

    return render_template("edit_template.html", template=template_data, form=newTemplateForm)


@email_blueprint.route('/campaigns')
def campaigns():
    return render_template("campaigns.html")


from .api.api import *

emailService/templates/campaigns.html
{% extends 'components/__MainLayout__.html' %}
{% block head %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('emailService.static', filename='css/campaigns.css') }}">
{% endblock %}
{% block content %}
<div class="container">
    <ul class="progress-bar">
        <li class="active-step">1</li>
        <li>2</li>
        <li>3</li>
    </ul>

    <form action="/submit-form" method="post">
        <div class="form-pages">
            <div class="form-page " id="firstPage">
                <div class="form-section">
                    <label for="campaignName">Campaign Name</label>
                    <input type="text" id="campaignName" name="campaignName" placeholder="Campaigns Name">
                </div>
                <div class="form-section">
                    <label for="Subject">Subject</label>
                    <input type="text" id="Subject" name="Subject" placeholder="This will be shown as email subject">
                </div>
            </div>
            <div class="form-page"  id="secondPage">

                <div class="form-section">
                    <div class="recipients-section my-4">
                        <label for="recipients">
                            <i class="fa-solid fa-square-check fa-lg" style="color: #63E6BE;"></i>
                            <span style="font-size: larger; font-weight: 700;">
                                To
                            </span>
                            <div class="recipients-info">
                                All subscribed contacts in the audience Orangeville Foot Clinic.
                                <span class="recipients-count">4,079 recipients</span>
                            </div>
                        </label>
                        <button type="button" class="edit-recipients-btn">Edit</button>
                    </div>
                    <div class="template-section my-4">
                        <label for="template">
                            <i class="fa-solid fa-square-check fa-lg" style="color: #ccc;"></i>
                            <span style="font-size: larger; font-weight: 700;">
                                Template
                            </span>
                            <div class="template-info">
                                Select a template or create <a href="">New template</a>
                            </div>
                        </label>
                        <button type="button" class="edit-recipients-btn">Select</button>
                    </div>
                    <div class="time-schedule-section my-4">
                        <label class="d-flex flex-column w-100 " for="time">
                            <div>
                                <i class="fa-solid fa-square-check fa-lg" style="color: #ccc;"></i>

                                <span style="font-size: larger; font-weight: 700;">

                                    Send time
                                </span>
                            </div>
                            <div class="schedule-info d-flex justify-content-between ">
                                Set Time when you want the emails to be sent
                                <button type="button" class="edit-recipients-btn">Edit</button>
                            </div>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-page " id="thirdPage">
                <div class="form-section">
                    <label for="campaignName">Campaign Name</label>
                    <input type="text" id="campaignName" name="campaignName" placeholder="Campaigns Name">
                </div>
                <div class="form-section">
                    <label for="Subject">Subject</label>
                    <input type="text" id="Subject" name="Subject" placeholder="This will be shown as email subject">
                </div>
            </div>
        </div>
        <div class="form-section d-flex justify-content-between">
            <button class="d-none" id="previous" type="submit">Previous Step</button>
            <button type="submit" id="next">Next Step</button>
        </div>
    </form>
</div>
<div id="dropdownOverlay"></div>
{% endblock %}

{% block footer %}
{{super()}}
<script>
    // Function to change the width
    function setProgressBarWidth(newWidth) {
        // Set the CSS variable
        document.documentElement.style.setProperty('--progress-bar-width', newWidth);
    }
    document.addEventListener('DOMContentLoaded', function () {
        const directionButtons = document.querySelectorAll('.form-section button[type="submit"]');
        const previousButton = directionButtons[0];
        const nextButton = directionButtons[1];
        const formPages = document.querySelector('.form-pages');
        const activeStep = document.querySelectorAll('.progress-bar li');
        let pageIndex = 0;

        nextButton.addEventListener('click', function (e) {
            e.preventDefault(); // Prevent the form from submitting for demonstration
            previousButton.classList.remove('d-none');
            pageIndex++;

            // Slide to the second page
            formPages.style.transform = `translateX(-${24*pageIndex}%)`;
            activeStep[pageIndex].classList.add('active-step');
            setProgressBarWidth(`${47 * pageIndex}%`); // Change width to 60%
        });

        previousButton.addEventListener('click', function (e) {

            e.preventDefault(); // Prevent the form from submitting for demonstration
            activeStep[pageIndex].classList.remove('active-step');
            pageIndex--;
            
            // Slide to the previous page   
            formPages.style.transform = `translateX(-${33*pageIndex}%)`;
            setProgressBarWidth(`${47 / (47 * pageIndex)}%`); // Change width to 60%


            if (pageIndex == 0) {
                previousButton.classList.add('d-none');
            }

        });
    });
</script>
{% endblock %}

emailService/templates/components/__MainLayout__.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %} <title>OrangeVille Foot Clinic Email Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('emailService.static', filename='css/filterForm.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('emailService.static', filename='css/global.css') }}">
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('emailService.static', filename='css/newTemplateForm.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.css"
          integrity="sha512-KuSX+43gVS5MEIJD2ewtrFPOHqC1PJnL8o2f5ciggPC0JUZ8XV0QXlfArO1mSzKkVFdRjsBDfrTU96C5SuRfqQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.js"
            integrity="sha512-1aNp9qKP+hKU/VJwCtYqJP9tdZWbMDN5pEEXXoXT0pTAxZq1HHZhNBR/dtTNSrHO4U1FsFGGILbqG1O9nl8Mdg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Include SweetAlert2 CSS and JS -->
    <script src="
https://cdn.jsdelivr.net/npm/sweetalert2@11.10.1/dist/sweetalert2.all.min.js
"></script>
    <link href="
https://cdn.jsdelivr.net/npm/sweetalert2@11.10.1/dist/sweetalert2.min.css
" rel="stylesheet">
    {{ bootstrap.load_css() }}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
</head>
<body>
<div class="wrap">
    {% block header %}
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <!-- user image -->
                <div class="round-widget">
                    <span>A</span>
                    <div class="dropdown-content" id="dropdown-content">
                        <!-- Your dropdown content goes here -->
                        <a href="#">Option 1</a>
                        <a href="#">Option 2</a>
                        <a href="#">Option 3</a>
                    </div>
                </div>

                <!-- Navbar toggler for small screens -->
                <button id="toggleLeftSide" class="navbar-toggler p-2" type="button">
                    <i class="fa-solid fa-angles-right fa-xl"></i>
                </button>

            </div>
        </nav>
    </header>
    {% endblock %}
    <main id="main">
        <div class="left-side" id="left-side">
            <div class="logo-wrap">
                <a href="/emailService"><img class="logo"
                                src="{{ url_for('emailService.static', filename='img/Orangville-foot-Logo-H.svg') }}"
                                alt=""></a>
            </div>
            <nav>
                <ul>
                    <li class="has-submenu"><a class="dropdown-nav" href="#templates"><i
                            class="fa-solid fa-file-lines fa-lg"></i><span>Templates</span><i
                            class="fa-solid fa-caret-down"></i></a>
                        <ul class="submenu collapse">
                            <li><a class="nav-link" href="{{url_for('emailService.template_creator')}}">Template
                                Creator</a></li>
                            <li><a class="nav-link" href="{{url_for('emailService.templates')}}">Templates List</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu"><a class="dropdown-nav" href="#scheduled"><i
                            class="fa-solid fa-address-card fa-lg"></i><span>Audience</span><i
                            class="fa-solid fa-caret-down"></i></a>
                        <ul class="submenu collapse">
                            <li><a class="nav-link" href="#">Submenu item 1 </a></li>
                            <li><a class="nav-link" href="#">Submenu item 2 </a></li>
                            <li><a class="nav-link" href="#">Submenu item 3 </a></li>
                        </ul>
                    </li>
                    <li class="has-submenu"><a class="dropdown-nav" href=""><i
                            class="fa-solid fa-users-rays "></i><span>Campaigns</span><i
                            class="fa-solid fa-caret-down"></i></a>
                        <ul class="submenu collapse">
                            <li><a class="nav-link" href="{{url_for('emailService.campaigns')}}">Create Campaign </a></li>
                            <li><a class="nav-link" href="#">Campaigns List </a></li>
                            <li><a class="nav-link" href="#">Automations </a></li>
                        </ul>
                    </li>
                    <li><a href="http://127.0.0.1:5002/analytics/"><i class="fa-solid fa-chart-simple fa-lg "></i><span>Analytics</span></a></li>
                </ul>
            </nav>
        </div>

        {% block content %}{% endblock %}
    </main>
</div>
</body>
<footer>
    {% block footer %}
    <!-- Initialize Spectrum Color Picker -->
    <script>
        $("#color-picker").spectrum({
            preferredFormat: "hex",
            showInput: true,
            showPalette: true,
            showPaletteOnly: true,
            togglePaletteOnly: true,
            palette: [
                ["#000", "#fff", "#808080", "#999999", "#cccccc", "#e6e6e6", "#f2f2f2"],
                ["#e60012", "#f39800", "#fff100", "#8fc31f", "#009944", "#009e96", "#00a0e9", "#0068b7", "#1d2088", "#920783"]
            ],
            containerClassName: 'sp-container', // Custom class for the container
            replacerClassName: 'sp-replacer', // Custom class for the color preview box
            replacerStyle: {border: '1px solid #ced4da', borderRadius: '.5rem'}, // Custom style for the color preview box
            showInitial: true,
            color: "#e60012" // Set the default color here

        });
    </script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://kit.fontawesome.com/ccdcc39714.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"></script>
    <script src="https://editor.unlayer.com/embed.js"></script>

    <script type="module" src="{{ url_for('emailService.static', filename='js/emailsScript.js') }}"></script>
    {{ bootstrap.load_js() }}
    {% endblock %}
</footer>
</html>

emailService/templates/components/patientCard.html
<div class="patient-card">
    <div class="color-code"><span style="display: none" class="color-code-value">{{email.template_color_code}}</span></div>
    <p class="pname">Patient: {{email.username}}</p>
    <p class="edate">Email Date: {{email.date}}</p>
    <p class="tname">{{email.template}}</p>
</div>

emailService/templates/components/patientCardList.html
<div class="patient-card">
    <p class="pname">{{email.username|word_truncate(1, '...')}}</p>
    <p class="edate">{{email.date}}</p>
    <p class="tname">{{email.template}}</p>
</div>

emailService/templates/components/templateCard.html
<div class="template-card">
    <!-- Include a hidden input field for CSRF token -->
    <input type="hidden" class="csrfTokenInput" value="{{ csrf_token }}">
    <div class="color-code" id="color-code"><span style="display: none" class="color-code-value">{{template.color}}</span></div>
    <p class="template-name">{{template.name}}</p>
    <p class="template-content">{{ template.content | truncate(length=100) }}</p>
</div>

emailService/templates/edit_template.html
{% extends 'components/__MainLayout__.html' %}
{% block head %}
{{ super() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
        integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}
{% block content %}
<div id="template-data" data-template='{{ template|tojson|safe }}'></div>

<div class="title-wrap d-flex w-100 justify-content-between align-items-center mb-2">
    <h2 class="mb-0">Edit {{ template.name }}</h2>
    <p class="mb-0 text-success">Autosave is active</p>
</div>


<div class="editor-wrap d-flex w-100 h-100" id="editor-wrap">
    <form method="POST" id="createTemplateForm">
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            {{ form.title(class="form-control template-name", value=template.name or "Default Name") }}
            {% for error in form.title.errors %}
            <span class="text-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="color" class="form-label">Color</label>
            <input type="text" id="color-picker" name="color" class="form-control" value="{{ template.color }}"/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary" id="createTemplate">Submit</button>
        </div>
    </form>
    <div class="flex-fill" id="editor" style="height: 100%"></div>
</div>
<div id="dropdownOverlay"></div>
{% endblock %}

{% block footer %}
{{super()}}
<script type="module" src="{{ url_for('emailService.static', filename='js/editTemplate.js') }}"></script>


{% endblock %}

emailService/templates/emails.html
{% extends 'components/__MainLayout__.html' %}

{% block head %}
{{super()}}
<link rel="stylesheet" type="text/css" href="{{ url_for('emailService.static', filename='css/emails.css') }}">
{% endblock %}

{% block content %}
<section id="search">
    <div class="search-container">
        <div class="search-input-wrapper">
            <i class="fas fa-search"></i>
            <input type="text" id="search-input" placeholder="Search...">
            <i id="filterBtn" class="fa-solid fa-filter" style="color: #888888; cursor: pointer;"></i>
        </div>
    </div>
</section>
<div class="title-wrap d-flex w-100 justify-content-between align-items-center mb-2">
    <h2 class="mb-0">Quick Action</h2>
</div>

<section id="quickAction">
    <div id="action-list">
        <a href="{{url_for('emailService.template_creator')}}" id="createTemplate" class="q-action-btn">
            <i class="fa-solid fa-plus fa-lg" style="color: green;"></i>
            Add Template
        </a>

        <button id="createCampaign" class="q-action-btn">
            <i class="fa-solid fa-plus fa-lg" style="color: green;"></i>
            Add Campaign
        </button>

        <button id="addContact" class="q-action-btn">
            <i class="fa-solid fa-plus fa-lg" style="color: green;"></i>
            <span>Add Contact</span>
        </button>
    </div>
</section>


<div class="title-wrap d-flex w-100 justify-content-between align-items-center mb-2">
    <h2 class="mb-0">Email Analytics</h2>
    <button class="show-more">
        Show More
    </button>
</div>

<section id="analytics">
    <div class="clicks-info">
        <p class="me-5" style="font-size: larger; font-weight: 600;">Clicks</p>
        <div class="contact-info m-3">
            <p class="d-flex justify-content-between align-items-center" style="text-align: left">Click
                Rate<i class="fa-solid fa-circle-info fa-lg" style="color: grey;"></i></p>
            <h2 style="text-align: center">00.00%</h2>
        </div>
        <div class="open-rate-info m-3">
            <p class="d-flex justify-content-between align-items-center" style="text-align: left">
                Open Rate<i class="fa-solid fa-circle-info fa-lg" style="color: grey;"></i></p>
            <h2 style="text-align: center">00.00%</h2>
        </div>
    </div>
    <div class="top-campaigns">
        <p style="font-size: larger; font-weight: 600;">Top Campaigns</p>
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>clicks</th>
                    <th>open rate</th>
                </tr>
            </thead>
            <tbody>
                <!-- Add your table rows here -->
                <tr>
                    <td><a href="">Food Drive Success! Winner ...</a></td>
                    <td>Email</td>
                    <td>100</td>
                    <td>67.00</td>
                    <td><i class="fa-solid fa-arrow-right fa-fade fa-lg" style="color: #005eff;"></i></td>
                </tr>
                <tr>
                    <td><a href="">Group 2</a></td>
                    <td>SMS</td>
                    <td>150</td>
                    <td>65.00</td>
                    <td><i class="fa-solid fa-arrow-right fa-fade fa-lg" style="color: #005eff;"></i></td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>
    </div>
</section>

<div class="title-wrap d-flex w-100 justify-content-between align-items-center mb-2">
    <h2 class="mb-0">Contacts & Groups</h2>
    <button class="show-more">
        Show More
    </button>
</div>

<section id="audience">
    <div class="contacts-info-wrap">
        <p class="me-5" style="font-size: larger; font-weight: 600;">Contacts & Subscribers</p>
        <div class="contact-info m-3">
            <p class="d-flex justify-content-between align-items-center" style="text-align: left">Contacts<i
                    class="fa-solid fa-plus fa-lg fa-beat" style="color: green;"></i></p>
            <h2 style="text-align: center">4001</h2>
        </div>
        <div class="subs-info m-3">
            <p class="d-flex justify-content-between align-items-center" style="text-align: left">Subscribers<i
                    class="fa-solid fa-circle-info fa-lg" style="color: grey;"></i></p>
            <h2 style="text-align: center">3999</h2>
        </div>
    </div>
    <div class="groups-info-wrap">
        <p style="font-size: larger; font-weight: 600;">Groups and Campaigns</p>
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Recipients</th>
                </tr>
            </thead>
            <tbody>
                <!-- Add your table rows here -->
                <tr>
                    <td><a href="">Food Drive Success! Winner ...</a></td>
                    <td>Email</td>
                    <td>100</td>
                    <td><i class="fa-solid fa-arrow-right fa-fade fa-lg" style="color: #005eff;"></i></td>
                </tr>
                <tr>
                    <td><a href="">Group 2</a></td>
                    <td>SMS</td>
                    <td>150</td>
                    <td><i class="fa-solid fa-arrow-right fa-fade fa-lg" style="color: #005eff;"></i></td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>
    </div>
</section>
<div id="emailContentOverlay">
    <div id="emailContent">
        <!-- Email content goes here -->
    </div>
</div>
<div id="templateContentOverlay">
    <div id="templateContent">
    </div>
</div>
<div id="NewTemplateContentOverlay">
    <div id="FormContent">
        <form method="POST" action="/" id="emailForm">
            {{ form.hidden_tag() }}

            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                {{ form.title() }}
                {% for error in form.title.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                {{ form.content() }}
                {% for error in form.content.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="mb-3">
                <label for="color" class="form-label">Color</label>
                <input type="text" id="color-picker" name="color" class="form-control" value="#e60012" />
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary" id="createNewTemplateSubmit">Submit</button>
            </div>
        </form>
    </div>

</div>

<div id="filterContentOverlay">
    <div id="filterModalContent">
        <!-- Email content goes here -->
    </div>
</div>
<div id="dropdownOverlay"></div>
{% endblock %}

emailService/templates/templates.html
{% extends 'components/__MainLayout__.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('emailService.static', filename='css/templates.css') }}">

{% endblock %}

{% block content %}
<div class="title-wrap d-flex w-100 justify-content-between align-items-center mb-2">
    <h2 class="mb-0">Template List</h2>
</div>

<div class="template-list-wrap h-100" id="template-list-wrap">
    <!-- Example: Repeat the following structure for each template -->
    {% for template in templates %}
    <div class="template-widget">
        <div class="overlay-icons">
            <!-- Add your delete and edit icons here -->
            <i class="fa-solid fa-trash fa-xl delete" style="color: #ff0000;"
               data-template-name="{{ template.name }}"></i>
            <a href="{{ url_for('emailService.edit_template', template_name=template.name) }}">
                <i class="fa-solid fa-pen-to-square fa-xl" style="color: #74C0FC;" id="edit"></i>
            </a>
        </div>
        <img class="template-image"
             src="{{ url_for('emailService.static', filename='uploads/img/' ~ template.imageUrl) }}"
             alt="Template Image {{ i }}">
        <div class="template-title">{{template.name}}</div>
    </div>
    {% endfor %}
    <!-- Repeat structure ends here -->
</div>
<div id="dropdownOverlay"></div>
{% endblock %}

{% block footer %}
{{ super() }}
<script type="module" src="{{ url_for('emailService.static', filename='js/templates.js') }}"></script>
<script>
    function handleEdit(icon) {
        // Handle edit action
        console.log('Edit clicked for widget', icon.closest('.template-widget'));
    }

    function handleDelete(icon) {
        // Handle delete action
        console.log('Delete clicked for widget', icon.closest('.template-widget'));
    }
</script>
{% endblock %}